### ISSUE TITLE
Code in heatmap is horizontally cut off

### ISSUE THREAD

**Issue by schmidtdominik** [csurfer/pyheatmagic#4]
The code in the heatmap sometimes gets cut off on the right.

![screenshot from 2017-08-24 17-56-30](https://user-images.githubusercontent.com/8918572/29675545-bd7b14fa-88f5-11e7-9971-048a81b1c87c.png)

**Comment by csurfer** [comment]
@schmidtdominik: Seems like a padding issue will resolve soon.

**Comment by schmidtdominik** [comment]
Awesome, thanks!

**Comment by csurfer** [comment]
@schmidtdominik This seems to be resolved by an upstream fix. Please let me know otherwise.
